INSERT INTO movies (user_id, movie_name, movie_id, genre, average_rating, main_actor1, main_actor2, director, year, review) VALUES
    (1, 'Inception', 148, 'Sci-Fi', 8.8, 'Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Christopher Nolan', 2010, 'Could watch Inception again and again.'),
    (2, 'The Dark Knight', 152, 'Action', 9.0, 'Christian Bale', 'Heath Ledger', 'Christopher Nolan', 2008, 'Not my favorite, but worth watching.'),
    (3, 'Pulp Fiction', 154, 'Crime', 8.9, 'John Travolta', 'Samuel L. Jackson', 'Quentin Tarantino', 1994, 'Highly recommended!'),
    (4, 'The Godfather', 175, 'Crime', 9.2, 'Marlon Brando', 'Al Pacino', 'Francis Ford Coppola', 1972, 'The Godfather is a classic.'),
    (5, 'The Shawshank Redemption', 142, 'Drama', 9.3, 'Tim Robbins', 'Morgan Freeman', 'Frank Darabont', 1994, 'Not my favorite, but worth watching.'),
    (1, 'The Matrix', 136, 'Sci-Fi', 8.7, 'Keanu Reeves', 'Laurence Fishburne', 'Lana Wachowski', 1999, 'Highly recommended!'),
    (2, 'Fight Club', 139, 'Drama', 8.8, 'Brad Pitt', 'Edward Norton', 'David Fincher', 1999, 'An excellent watch!'),
    (3, 'Forrest Gump', 142, 'Drama', 8.8, 'Tom Hanks', 'Robin Wright', 'Robert Zemeckis', 1994, 'An excellent watch!'),
    (4, 'The Lord of the Rings: The Return of the King', 201, 'Fantasy', 8.9, 'Elijah Wood', 'Viggo Mortensen', 'Peter Jackson', 2003, 'Exceptional performance by the cast!'),
    (5, 'Interstellar', 169, 'Sci-Fi', 8.6, 'Matthew McConaughey', 'Anne Hathaway', 'Christopher Nolan', 2014, 'Not my favorite, but worth watching.'),
    (1, 'The Lion King', 88, 'Animation', 8.5, 'Matthew Broderick', 'Jeremy Irons', 'Roger Allers', 1994, 'Highly recommended!'),
    (2, 'Gladiator', 155, 'Action', 8.5, 'Russell Crowe', 'Joaquin Phoenix', 'Ridley Scott', 2000, 'Not my favorite, but worth watching.'),
    (3, 'Titanic', 195, 'Romance', 7.8, 'Leonardo DiCaprio', 'Kate Winslet', 'James Cameron', 1997, 'Exceptional performance by the cast!'),
    (4, 'Avatar', 162, 'Sci-Fi', 7.8, 'Sam Worthington', 'Zoe Saldana', 'James Cameron', 2009, 'Could watch Avatar again and again.'),
    (5, 'The Avengers', 143, 'Action', 8.0, 'Robert Downey Jr.', 'Chris Evans', 'Joss Whedon', 2012, 'Not my favorite, but worth watching.'),
    (1, 'Jurassic Park', 127, 'Adventure', 8.1, 'Sam Neill', 'Laura Dern', 'Steven Spielberg', 1993, 'Could watch Jurassic Park again and again.'),
    (2, 'Star Wars: Episode IV - A New Hope', 121, 'Sci-Fi', 8.6, 'Mark Hamill', 'Harrison Ford', 'George Lucas', 1977, 'Could watch Star Wars: Episode IV - A New Hope again and again.'),
    (3, 'Back to the Future', 116, 'Adventure', 8.5, 'Michael J. Fox', 'Christopher Lloyd', 'Robert Zemeckis', 1985, 'Not my favorite, but worth watching.'),
    (4, 'The Silence of the Lambs', 118, 'Thriller', 8.6, 'Jodie Foster', 'Anthony Hopkins', 'Jonathan Demme', 1991, 'An excellent watch!'),
    (5, 'Schindler\'s List', 195, 'Biography', 8.9, 'Liam Neeson', 'Ralph Fiennes', 'Steven Spielberg', 1993, 'Highly recommended!'),
    (1, 'The Green Mile', 189, 'Drama', 8.6, 'Tom Hanks', 'Michael Clarke Duncan', 'Frank Darabont', 1999, 'Could watch The Green Mile again and again.'),
    (2, 'Saving Private Ryan', 169, 'Drama', 8.6, 'Tom Hanks', 'Matt Damon', 'Steven Spielberg', 1998, 'Not my favorite, but worth watching.'),
    (3, 'Braveheart', 178, 'Action', 8.3, 'Mel Gibson', 'Sophie Marceau', 'Mel Gibson', 1995, 'Exceptional performance by the cast!'),
    (4, 'Goodfellas', 146, 'Crime', 8.7, 'Robert De Niro', 'Ray Liotta', 'Martin Scorsese', 1990, 'Not my favorite, but worth watching.'),
    (5, 'The Departed', 151, 'Crime', 8.5, 'Leonardo DiCaprio', 'Matt Damon', 'Martin Scorsese', 2006, 'Highly recommended!'),
    (1, 'The Prestige', 130, 'Drama', 8.5, 'Christian Bale', 'Hugh Jackman', 'Christopher Nolan', 2006, 'Highly recommended!'),
    (2, 'Memento', 113, 'Mystery', 8.4, 'Guy Pearce', 'Carrie-Anne Moss', 'Christopher Nolan', 2000, 'Highly recommended!'),
    (3, 'The Pianist', 150, 'Biography', 8.5, 'Adrien Brody', 'Thomas Kretschmann', 'Roman Polanski', 2002, 'Highly recommended!'),
    (4, 'Gladiator', 155, 'Action', 8.5, 'Russell Crowe', 'Joaquin Phoenix', 'Ridley Scott', 2000, 'Not my favorite, but worth watching.'),
    (5, 'Terminator 2: Judgment Day', 137, 'Action', 8.5, 'Arnold Schwarzenegger', 'Linda Hamilton', 'James Cameron', 1991, 'Highly recommended!'),
    (1, 'Whiplash', 106, 'Drama', 8.5, 'Miles Teller', 'J.K. Simmons', 'Damien Chazelle', 2014, 'An excellent watch!'),
    (2, 'The Lion King', 88, 'Animation', 8.5, 'Matthew Broderick', 'Jeremy Irons', 'Roger Allers', 1994, 'Highly recommended!'),
    (3, 'The Intouchables', 112, 'Biography', 8.5, 'François Cluzet', 'Omar Sy', 'Olivier Nakache', 2011, 'Not my favorite, but worth watching.'),
    (4, 'The Great Dictator', 125, 'Comedy', 8.4, 'Charles Chaplin', 'Paulette Goddard', 'Charles Chaplin', 1940, 'Could watch The Great Dictator again and again.'),
    (5, 'The Green Mile', 189, 'Drama', 8.6, 'Tom Hanks', 'Michael Clarke Duncan', 'Frank Darabont', 1999, 'Could watch The Green Mile again and again.'),
    (1, 'Parasite', 132, 'Thriller', 8.6, 'Kang-ho Song', 'Sun-kyun Lee', 'Bong Joon Ho', 2019, 'Could watch Parasite again and again.'),
    (2, 'Interstellar', 169, 'Sci-Fi', 8.6, 'Matthew McConaughey', 'Anne Hathaway', 'Christopher Nolan', 2014, 'Highly recommended!'),
    (3, 'Leon: The Professional', 110, 'Crime', 8.5, 'Jean Reno', 'Gary Oldman', 'Luc Besson', 1994, 'An excellent watch!'),
    (4, 'Harakiri', 133, 'Drama', 8.6, 'Tatsuya Nakadai', 'Akira Ishihama', 'Masaki Kobayashi', 1962, 'Could watch Harakiri again and again.'),
    (5, 'Casablanca', 102, 'Romance', 8.5, 'Humphrey Bogart', 'Ingrid Bergman', 'Michael Curtiz', 1942, 'Could watch Casablanca again and again.'),
    (1, 'Modern Times', 87, 'Comedy', 8.5, 'Charles Chaplin', 'Paulette Goddard', 'Charles Chaplin', 1936, 'Could watch Modern Times again and again.');
