# Generated by Django 5.0.7 on 2024-07-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Nonbinary', 'Nonbinary')], default='Male', max_length=10),
            preserve_default=False,
        ),
    ]
