# Generated by Django 5.0.7 on 2024-07-11 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movie_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=127)),
                ('movie_description', models.TextField()),
                ('movie_image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='MovieUserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('review', models.TextField()),
                ('movie_id', models.ForeignKey(db_column='movies_id', on_delete=django.db.models.deletion.CASCADE, to='app_main.movies')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='members.userinfo')),
            ],
        ),
    ]
